groups:
  - name: example
    rules:
      - alert: HighLoad
        expr: node_load1 > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High load on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a high load of {{ $value }}."
