global:
  scrape_interval: 5s

rule_files:
  - "/etc/prometheus/rules.yml"
  - "/etc/prometheus/alert.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nodeexporter'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'mysqlexporter'
    static_configs:
      - targets: ['mysqlexporter:9104']

  - job_name: 'apacheexporter'
    static_configs:
      - targets: ['apacheexporter:9117']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://web:80
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackboxexporter:9115
